---
- name: Remove existing project dir
  file:
    path: "{{ project_path }}/"
    state: absent
  when: nuke_current_project

- name: Create new project dir
  file:
    path: "{{ project_path }}/"
    state: directory
    owner: "{{ users_name }}"
    group: "{{ users_group }}"
    mode: 0755

- name: Clone project repo
  become: true
  become_user: "{{ users_name }}"
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_path }}"
    version: "{{ git_branch }}"
    force: yes
    accept_hostkey: yes
  when: uses_git

- import_tasks: setEnvFile.yml
  when: uses_env_file

- name: Composer install
  become: true
  become_user: "{{ users_name }}"
  composer:
    command: "{{ composer_action }}"
    no_dev: "{{ composer_no_dev }}"
    optimize_autoloader: yes
    working_dir: "{{ project_path }}"
    arguments: --quiet
    executable: "{{ composer_php_executable }}"
  when: uses_composer


- import_tasks: doctrine.yml
  when: uses_doctrine

- import_tasks: sslClientCerts.yml
  when: use_ssl_client_cert

- import_tasks: nginx.yml
  when: config_nginx_for_domain
